name: Playwright Tests
on:
  push:
    branches: [ clean-main ]
  pull_request:
    branches: [ clean-main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    # Define environment variables for the tests
    env:
      BASE_URL: https://automationexercise.com
      USER_NAME: "Riza Gencalp"
      PASSWORD: "123456"
      TEST_EMAIL: "rizagencalp@gmail.com"
      TEST_PASSWORD: "123456"
      APITEST_EMAIL: "yasemincak@gmail.com"
      APITEST_PASSWORD: "123456"

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30